#!/bin/bash
# PostToolUse hook for PRISM integration
# Auto-generated by PRISM Phase 4B implementation

TOOL_NAME="$1"
FILE_PATH="$2"
SESSION_ID="$3"

# Only for code tools
[[ ! "$TOOL_NAME" =~ ^(Write|Edit|MultiEdit|NotebookEdit)$ ]] && exit 0

# Read file content
CODE=$(cat "$FILE_PATH" 2>/dev/null) || exit 0

# Pattern detection (async)
(
    curl -s -X POST http://localhost:8090/api/hooks/post-tool-use \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer prism_development_key_2024" \
        -d "{
            \"tool_name\": \"$TOOL_NAME\",
            \"file_path\": \"$FILE_PATH\",
            \"session_id\": \"$SESSION_ID\",
            \"file_content\": $(echo "$CODE" | jq -Rs .)
        }" \
        >> ~/.local/share/prism_mcp/logs/hooks.log 2>&1 &
) &

exit 0