#!/bin/bash
# PreToolUse hook for PRISM integration
# Auto-generated by PRISM Phase 4B implementation

TOOL_NAME="$1"
FILE_PATH="$2"
SESSION_ID="$3"

# Only for code files
[[ ! "$FILE_PATH" =~ \.(py|js|ts|tsx|go|rs|java|cpp|c|h)$ ]] && exit 0

# Query PRISM (lightning mode, <100ms)
RESULT=$(curl -s -m 0.1 -X POST http://localhost:8090/api/hooks/pre-tool-use \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer prism_development_key_2024" \
    -d "{
        \"tool_name\": \"$TOOL_NAME\",
        \"file_path\": \"$FILE_PATH\",
        \"session_id\": \"$SESSION_ID\"
    }" 2>/dev/null)

# Parse response
SHOULD_BLOCK=$(echo "$RESULT" | jq -r '.should_block // false' 2>/dev/null)
BLOCK_REASON=$(echo "$RESULT" | jq -r '.block_reason // ""' 2>/dev/null)
PATTERNS=$(echo "$RESULT" | jq -r '.context_patterns[]? // ""' 2>/dev/null)

# Block if critical pattern detected
if [[ "$SHOULD_BLOCK" == "true" ]]; then
    echo "🚨 CRITICAL PATTERN DETECTED: $BLOCK_REASON"
    exit 1
fi

# Inject context patterns
if [[ -n "$PATTERNS" ]]; then
    echo "📋 Relevant patterns:"
    echo "$PATTERNS"
fi

exit 0