"""m32rimm-specific patterns and context.

This module provides project-specific context that gets injected into
orchestration prompts to help agents understand m32rimm conventions.
"""

from .prompts import get_full_context

# Full context string for prompt injection
CONTEXT = get_full_context()


def get_context() -> str:
    """Get the full m32rimm context for prompt injection.

    This is called by the extensions system when building prompts.
    """
    return CONTEXT


# Common gotchas that should be mentioned in specs
COMMON_GOTCHAS = [
    'DBOpsHelper requires .flush() before aggregating - missed flushes cause stale grid data',
    'Activities in dedicated collection - DBOpsHelper auto-reroutes when writing to businessObjects',
    'Selectizer lookup: sub_id first, then global (None) - unless only_sub_selectizer=True',
    'related.* for simple ID arrays, relatedV2 for rich relationships - aggregations use related.*',
    'toolIDs is a LIST of objects: [{toolName, id, url}] - query with data.toolIDs.toolName',
    'Multiprocessing needs separate connections for MongoDB, Redis, any network resource',
    'mark_for_aggregation() just builds dict - call_clustereng_tps_owasp_aggs() actually triggers',
    'Grid collections regenerated by aggregation - never manually edit',
    'data_importer tracking NOT required for all imports - only when audit trail specified',
    'get_utc_now(naive=True) for MongoDB - MongoDB requires naive datetimes',
]

# Key utilities and their imports
KEY_UTILITIES = {
    'mongo_helpers': {
        'import': 'from fisio.common.mongo_helpers import retry_run, DBOpsHelper, find_one_or_none',
        'usage': 'Wrap all MongoDB writes with retry_run(), use DBOpsHelper for batching',
    },
    'date_utils': {
        'import': 'from fisio.common.date_utils import get_utc_now',
        'usage': 'Always use get_utc_now(naive=True) for MongoDB timestamps',
    },
    'bo_utils': {
        'import': 'from fisio.common.bo_utils import BOUpsert',
        'usage': 'Use BOUpsert.upsert_bo() for creating business objects',
    },
    'toolnames': {
        'import': 'from fisio.common.toolnames import TOOL_NAMES',
        'usage': 'Use constants for tool names instead of strings',
    },
}


__all__ = [
    'COMMON_GOTCHAS',
    'CONTEXT',
    'KEY_UTILITIES',
    'get_context',
]
