# golangci-lint configuration for production-ready Go code
# Optimized for financial/trading applications

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - Godeps
    - builtin
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    # Deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    
    # Too strict or noisy
    - wsl
    - wrapcheck
    - varnamelen
    - nlreturn
    - gochecknoglobals
    - gomnd
    - exhaustive
    - forbidigo
    - funlen
    - gocognit
    - cyclop
    - maintidx
    
    # May re-enable later
    - testpackage
    - paralleltest

linters-settings:
  # Error handling
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  # Code complexity
  gocyclo:
    min-complexity: 15
  
  nestif:
    min-complexity: 5
  
  # Code quality
  govet:
    enable-all: true
    check-shadowing: true
  
  revive:
    enable-all-rules: true
    rules:
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: add-constant
        disabled: true
      - name: cognitive-complexity
        arguments: [15]

  # Financial application specific
  gosec:
    excludes:
      - G101 # We might have test API keys
    config:
      G306: "0600" # File permissions for sensitive data
      G301: "0750" # Directory permissions
  
  # Performance
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  # Style and formatting
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/forex-trader,github.com/yourusername
  
  gofumpt:
    extra-rules: true
  
  misspell:
    locale: US
  
  # Testing
  testifylint:
    enable-all: true
  
  # Concurrency - critical for trading systems
  gorace:
    enabled: true
  
  # Decimal handling for financial calculations
  goconst:
    min-len: 3
    min-occurrences: 3
    numbers: true # Flag magic numbers
  
  # Naming conventions
  stylecheck:
    checks:
      - all
      - -ST1003 # Allow underscores in test names
  
  # Dependencies
  gomoddirectives:
    replace-allow-list:
      - github.com/shopspring/decimal # Allow decimal library
  
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use stdlib errors with fmt.Errorf and %w"
          - pkg: "float32"
            desc: "Use decimal types for financial calculations"
          - pkg: "float64"
            desc: "Use decimal types for financial calculations"
  
  # Documentation
  godot:
    scope: declarations
    capital: true
    period: true
  
  # Unused code
  unparam:
    check-exported: true
  
  unused:
    check-exported: false
  
  # Type checking
  asasalint:
    use-builtin-exclusions: true
  
  # Error wrapping
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - goconst
        - funlen
        - cognitive-complexity
    
    # Exclude benchmarks from complexity checks
    - path: _bench\.go
      linters:
        - gosec
        - goconst
        - funlen
    
    # Allow init functions
    - linters:
        - gochecknoinits
      source: "^func init\\(\\)"
    
    # Allow TODO/FIXME comments in development
    - linters:
        - godox
      text: "TODO|FIXME|BUG"

severity:
  default-severity: warning
  rules:
    # Critical for financial applications
    - linters:
        - gosec
        - gorace
        - errcheck
        - staticcheck
      severity: error
    
    # Important for code quality
    - linters:
        - govet
        - ineffassign
        - typecheck
      severity: error
